### ISSUE TITLE
How exactly to put it into my webpack?

### ISSUE THREAD

**Issue by Kuchiriel** [JavascriptIsMagic/shebang-loader#2]

**Comment by robinbandzar** [comment]
```
{
  test: /node_modules\/JSONStream\/index\.js$/,
  loaders: ['shebang', 'babel']
}

```
add that into your module loaders, in my case JSONStream was the culprit

**Comment by AhmedAKhan** [comment]
Thanks for your help, saved me alot of hassle :) , but can you please add this to the readme

**Comment by aliomar** [comment]
Ty for the help @robinbandzar

**Comment by Kuchiriel** [comment]
^^

**Comment by fxlemire** [comment]
As a quick note for webpack 3 users on Windows, the above solution won't work because of the path separators (`/` vs `\`). The following will:

```
module: {
  rules: [
    {
      test: path.resolve(__dirname, 'node_modules/jsonstream/index.js'),
      use: 'shebang-loader',
    },
  ],
},
```
